export enum UpaMessageId {
  SALE = "Sale",
  VOID = "Void",
  REFUND = "Refund",
  EOD = "EODProcessing",
  SENDSAF = "SendSAF",
  TIPADJUST = "TipAdjust",
  CARD_VERIFY = "CardVerify",
  GET_SAF_REPORT = "GetSAFReport",
  CANCEL = "CancelTransaction",
  REBOOT = "Reboot",
  LINEITEM = "LineItemDisplay",
  REVERSAL = "Reversal",
  GET_BATCH_REPORT = "GetBatchReport",
  BALANCE_INQUIRY = "BalanceInquiry",
  PRE_AUTH = "PreAuth",
  AUTH_COMPLETION = "AuthCompletion",
  TOKENIZE = "Tokenize",
  GET_OPEN_TAB_DETAILS = "GetOpenTabDetails",
}
